id: P008028
initial_creation_type: ocr
source_metadata:
  id: bdr:W14260
  title: གསང་འདུས་སྒྲོན་མ་རབ་གསལ་གྱི་རྒྱ་ཆེར་བཤད་པ།
  author: ''
  volumes:
    11b3b26bf35e496e822629ddae5afbc7:
      image_group_id: I1KG5215
      title: ''
      volume_number: 1
      total_pages: 940
ebook_metadata:
  title: གསང་འདུས་སྒྲོན་མ་རབ་གསལ་གྱི་རྒྱ་ཆེར་བཤད་པ།
  author: ''
  sku: P008028
  cover: cover.jpg
  layers:
  - pagination
